#ifndef HKY_SYS_CONFIG_H_INCLUDED
#define HKY_SYS_CONFIG_H_INCLUDED

#ifndef HKY_MAX_SIZE_T_VALUE
#define HKY_MAX_SIZE_T_VALUE 9223372036854775807LL
#endif // HKY_MAX_SIZE_T_VALUE

#ifndef HKY_MAX_OFF_T_VALUE
#define HKY_MAX_OFF_T_VALUE 9223372036854775807LL
#endif // HKY_MAX_OFF_T_VALUE

#ifndef HKY_MAX_TIME_T_VALUE
#define HKY_MAX_TIME_T_VALUE 9223372036854775807LL
#endif // HKY_MAX_TIME_T_VALUE

#ifndef HKY_ERROR_LOG_PATH
#define HKY_ERROR_LOG_PATH "logs/error.log"
#endif // HKY_ERROR_LOG_PATH

#ifndef HKY_HTTP_LOG_PATH
#define HKY_HTTP_LOG_PATH "logs/access.log"
#endif // HKY_HTTP_LOG_PATH

#ifndef HKY_SIZE_T_LEN
#define HKY_SIZE_T_LEN (sizeof("-9223372036854775808")-1)
#endif // HKY_SIZE_T_LEN

#ifndef HKY_CONF_PATH
#define HKY_CONF_PATH   "conf/husky.conf"
#endif // HKY_CONF_PATH

#endif // HKY_SYS_CONFIG_H_INCLUDED
